import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} mx-auto min-h-screen max-w-screen-md bg-black px-4 pb-4 text-neutral-100 lg:px-0 lg:pb-8`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
